version: '3'
services:
  insurance_env:
    network_mode: host
    # The next line defines the image that will be used to create the container
    # It refers to an image that is available on Docker Hub and uses the form:
    # NAMESPACE/REPO_NAME:TAG
    # Change this line if you want to change the image used for your container.
    image: kwhadocker/insurance-requirements:latest
    environment:
       - "MYUSER=${USER}"
    ports:
      # Jupyter default port
      - "8888:8888"
      # Postgres default port
      - "5432:5432"
    volumes:
      # Jupyter notebook password and config files
      - ~/.jupyter:/root/.jupyter
      # Insurance venv
      - ~/.virtualenvs/repos/insurance:/root/insurance-workspace
      # Insurance and marvin codebases
      - ~/insurance/:/root/insurance
      # SSH agent to access VPN
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh:/root/.ssh
      # Git permissions
      - ~/.gitconfig:/root/.gitconfig
    # Allows for interactive sessions
    tty: true #
